### ISSUE TITLE
no numpy module found although it is installed

### ISSUE THREAD

**Issue by kdarras** [patriceguyot/Acoustic_Indices#4]
Hi there, thanks for the useful repo!

However, when I tried running the main_test_indices.py file after fetching the entire repo on Ubuntu 20.04 and making sure that all 4 required packages were installed with PIP and also APT, I was unsuccessful:

```
 python main_test_indices.py
Traceback (most recent call last):
  File "main_test_indices.py", line 16, in <module>
    from compute_indice import *
  File "/home/kdarras/Documents/Boulot/2020 Hangzhou/ecoSound-web/indices/Acoustic_Indices/compute_indice.py", line 23, in <module>
    from scipy import signal, fftpack
  File "/usr/lib/python3/dist-packages/scipy/__init__.py", line 62, in <module>
    from numpy import show_config as show_numpy_config
ImportError: No module named numpy
```
please advise whether this is a bug or an error on my part.

**Comment by estabenau** [comment]
I'm glad you are giving it a shot. That error indicates numpy isn't
installed. If you can just try this from a command line, open python from
inside the python she'll import numpy. If that fails it means you don't
have numpy installed or at least not properly.. A quick Google search will
find instructions to install numpy for your particular setup.

As for the acoustic package, it remains a work in progress. I've had mixed
results with some of the analysis so be cautious on interpretation.

Good luck

**Comment by kdarras** [comment]
Thanks a lot for checking this. Weird... I had the impression I installed all required packages with APT and PIP. Now that numpy has been (re-?) installed with APT, I got to the next error message, which looks a little different:

```
python main_test_indices.py
Traceback (most recent call last):
  File "main_test_indices.py", line 16, in <module>
    from compute_indice import *
  File "/home/kdarras/Documents/Boulot/2020 Hangzhou/ecoSound-web/indices/Acoustic_Indices/compute_indice.py", line 23, in <module>
    from scipy import signal, fftpack
  File "/usr/lib/python3/dist-packages/scipy/__init__.py", line 119, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/usr/lib/python3/dist-packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: cannot import name _ccallback_c

```
